### ISSUE TITLE
Section 2.5 activity count seems too high

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1002]
There only seems like there are 2 activity counts on the section 2.5.
The view of the page and the t/f problem.
![image](https://user-images.githubusercontent.com/28868409/29146590-b465d1b0-7d16-11e7-89de-2faa3336ee8b.png)

**Comment by bnmnetp** [comment]
You are correct.

The problem is that I have another user that has a highly customized course.  His course added two new activities to this section.  But your students could never do them because they are not in your book 😭 

All courses with the same "base course"  i.e. thinkcspy share the same questions.

The solution is to give him his own base course so the questions don't cause trouble.

Then I'll have to delete all of his questions and rebuild thinkcspy.

**Comment by bnmnetp** [comment]
Further note -- Deleting all of those questions may mess up some assignments.  -- remember the problems we had with questions disappearing from assignments!
