### ISSUE TITLE
Login from Runestone Interactive not recognized at Runestone Academy

### ISSUE THREAD

**Issue by roldach99** [RunestoneInteractive/RunestoneServer#1010]
I have an account on Runestone Interactive.  The Runestone Academy page instructed me to login using that account.  When I attempt to login, it doesn't recognize me.

**Comment by bnmnetp** [comment]
Hmm, are you coming from the instructors page?  The instructions there say to "make an account"

<img width="502" alt="screenshot 2017-08-14 09 37 23" src="https://user-images.githubusercontent.com/51115/29276431-3e9037fc-80d4-11e7-8bb3-119b16963130.png">

I did not transfer any account or database information from one system to the other so that we could make a clean start.  If the instructions somewhere else led you to believe they would be please let me know.

**Comment by roldach99** [comment]
The screen below is from Runestone Academy.  It asks the user to login
using their Runestones Interactive Account:

[image: Inline image 1]

Richard Oldach
508-330-3063
