### ISSUE TITLE
When refreshing Assignment page, Activecode assignment shows original code

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1022]
Steps followed:
1. Created assignment with lhs_sample_activecode
2. Went to assignment page and edited the code with a "print ('hi')"
3. Refreshed the page
4. The activecode window defaults back to showing the original '# your code here'
5. Edit the code some more, adding just more random code
6. Running through the time scrubber, I see the original print statement from step 2. So, the edits were saved originally.

For two other problems, like mchoice or fillinblanks, the previous selections were saved and refreshed OK.  So, this is unique to the activecode refreshing.

**Comment by bnmnetp** [comment]
Yes, the default behavior for activecodes is to always show the original code.  We did that partly for load reasons so that for pages with lots of code we wouldn't need to unnecessarily load up all the code and changes the student had made.  Its also a comfort factor to know that the students could get back to a "safe spot" if they were chanting things.

**Comment by psmaker** [comment]
OK, I do see that the Load History button can be pressed to get their latest code.  That works as long as the student understands and doesn't freak out and think all their work is gone - and then starts typing it in all over again.  I will need to make sure the students are aware of this.

Thanks!
