### ISSUE TITLE
Gradebook assignment contains duplicate items and autograder records incorrect score

### ISSUE THREAD

**Issue by sschaub** [RunestoneInteractive/RunestoneServer#1041]
Repro steps:

1. Create a new thinkcspy course
1. Create a new assignment. For the assignment readings, select from the Simple Python Data chapter the following sections: Variable Names and Keywords; Statements and Expressions. Leave all assignment options at their defaults.
1. Navigate to those two sections in the book and complete the activities.
1. Navigate to Grading. Select the assignment and choose Autograde.
1. Navigate to Student Progress and select Gradebook.

Expected: Student earns 100%
Actual: Student earns 150% and duplicate entries appear in gradebook.

![image](https://user-images.githubusercontent.com/5494160/30347451-12d9baf8-97da-11e7-8b0a-382f39c7e669.png)

![image](https://user-images.githubusercontent.com/5494160/30347413-f6b22ca2-97d9-11e7-8e27-3e93826a7cf7.png)

**Comment by bnmnetp** [comment]
This problem stems from the same root as #1045 and #1038.

The main problem is that the web2py database access method update_or_insert appears to be a bit flakey.  Probably a multi-threading problem.   This was causing duplicate entries to be made into the database for individual student scores. I suspect it largely comes from someone clicking twice (or more) on the autograde button either intentionally or unintentionally.

The duplicate student problem was just a bad design for generating the gradebook table.

Last weekend I fixed both.

1. I removed the duplicates, keeping the first score.
2. I added a constraint to the database table so that now postgres itself prevents duplicates from getting into the table.
3. I rewrote the controller that generates the gradebook to be more robust in the face of students with the same first and last names (normally duplicate registrations).

So far so good.  If you are still experiencing either of these problems let me know so I can look into it further.
