### ISSUE TITLE
Autograde grades exercises submitted after due date

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1051]
I have students that did an exercise after the due date for the assignment. When I autograded (selecting only check before due date) the students received scores greater than zero.

**Comment by haugrud** [comment]
It seems that auto-grading is adjusting the time by the time zone but manual grading just uses GMT. If so, we need to be consistent.

**Comment by bnmnetp** [comment]
I thought we were being consistent.  I had gone through this carefully in an earlier issue.  Everything on the server side is stored in UTC.  I'll have to look into it more and see whats going on.

**Comment by bnmnetp** [comment]
I think we've been doing this at least partly wrong.  It would be better if we stored the due date in UTC time when the assignment is created.  I thought that was happening but that does not seem to be the case, at least not with the latest date/time selector.

I have a branch started that converts the assignment due date to UTC time when the assignment is created.  Now  I need to double back and make sure I'm not over-correcting during autograding.

This will also be a good unit test test case for the new test database I created.

**Comment by bnmnetp** [comment]
@presnick @tababbitt 

This is probably a good open issue to use for discussing time zone issues.

As I mentioned on slack, I think the solution should be to:

1.  Continue to store everything on the server in UTC time.  Right now this is happening by default because the server is set up to use utc time.  But we should ensure consistency by using datetime.utcnow() rather than datetime.now in the controller code.

2. When an assignment is created we should convert the time submitted to universal time.  This makes the database consistent and should ensure that autograder stuff "just works" without inserting timezone offsets from a session cookie.

3. User interface elements should convert times to local time for display, including:

* When editing previously creating assignments
* The history slider for activecodes
* the student progress pages that show assignment deadlines
* The assignment page that shows the list of assignments for a course
