### ISSUE TITLE
Student Progress - getting slower and slower

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1054]
When selecting the Student Progress tab, it is getting slower and slower to render the page to the point where it gives a 504 timeout occasionally.

Our ultimate goal is to get to the Gradebook - but sometimes getting there is slowed down by not being able to get to the Student Progress page.

I'm just concerned that as we get farther into the book (we are in Unit 9), that the performance will degraded to the point that we might not be able to get to the Gradebook anymore.

So, I'm wondering if there is some way to modify things so it doesn't timeout in getting to the Student Progress page.

**Comment by bnmnetp** [comment]
I've noticed that it is slower as well.  That may be due to the increased number of courses in action, but may also be an indication I'm missing an index somewhere in the database or that we have a query that is not as efficient as it should be.

Because this is also a really busy time of the semester for me, I will do my best but I don't know how much time I can put into this right now.

It seems that if getting to the gradebook is the key, then you could simply make a bookmark to the gradbook page. and use that.  I could also look into making a direct link to the gradebook available from somewhere else in the UI outside of the Student Progress tab.

I fully agree this needs to be faster and I'm sure that can happen.

Brad

**Comment by psmaker** [comment]
Actually, the bookmark idea is a perfectly fine solution for now. It takes me right where I want to go.

It is not necessary to make a direct link in that case.

**Comment by bnmnetp** [comment]
I spent some time today poking around nginx configurations.  I believe that I have increased the timeout value causing the 504 errors.   This should help with autograding as well as student progress tab.

I also created a few database indexes where it seemed obvious they would help.  I also found a couple of places where I think the code is working harder than it needs to, but fixing it is not a quick fix and I should probably prove to myself that it will be worth it.

Right now I don't forsee getting to any of the hard stuff until Christmas break.
