### ISSUE TITLE
Migration issues with the unittests

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#1066]
To run the grading unit tests, we:

1. drop the existing test db
2. create it from sql dump file
3. run the autograder to see if it generates the same score that's scored

During step 3, web2py loads up, which causes it to run all its migration logic. In particular, it looks at the DB metada in the databases folder. Those file names seem to be based on just the appname and the table name. It compares the models in the current code to the schemas of the currently loaded DB (or or, rather, the metadata in the files). If there's a mismatch, then it tries to run a migration. It's very important that the metadata in the files match the actual DB structure. It's OK if models don't, because they will cause migrations that change both the actual DB structure and the metadata in the files.

Any operation that changes the DB structure but leaves the metadata unchanged will make them be out of sync, and auto-migrations will not solve that problem.

Our first problem is that the metadata files end up being shared between any DBs that are accessed with different dburl strings, given the file naming convention.  That means if we switch between the actual database and the unittest database by changing connection strings, and the metadata files are unchanged, we will  have DB and metadata out of sync.

Our second problem is that even within unittests, if we run them twice we will have a problem. When we drop the existing test db and load it from the SQL dump, if migrations were done on the first time but the db wasn't redumped, the load from the SQL dump file will yield a DB state that doesn't match the metadata.

I don't have a solution to this problem yet, but I wanted to cleanly lay it out so that I (and others) could think about it clearly.

**Comment by bnmnetp** [comment]
I agree that we need careful thought on this one.

The current naming convention for the database files is considered best practice by the web2py community.  Otherwise the migration files are named by hashing the connection string, which comes with its own set of problems.  I remember this causing lots of headaches very early on in development.

One option to consider would be to have db.py notice the value of WEB2PY_CONFIG and have it turn off migration when it creates the db object.  If our unit test database and the schema definitions in our development environment are not in sync, that probably means we should do something manually to update our test database.

**Comment by bnmnetp** [comment]
Test
