### ISSUE TITLE
Auto Grading on assignments. 

### ISSUE THREAD

**Issue by MrShaunMcG** [RunestoneInteractive/RunestoneServer#1083]
I use assignments in this way, set Reading and Exercise assignments. example( Reading CH 4 & Exercises CH 4). I set **Reading** pages/quesitons for Reading assignments including the chapters exercises (of which I require 5 to be done) and **Problem** exercises for the Exercises assignments. When I run the auto-grading on the Reading assignments, I receive the grades as would expect in the progress/grade book. However, when I run the auto-grading for the Exercise (Problem) assignments, the drop down console box doesn't display any totals and the gradebook says 0%. Is this because we (tutors) are supposed to be manually grading the **Problem** exercises? If this is the expected output, I can adapt how I use the book. I just need to know whether this is a fault or not. I am completely okay with being told my way of using the book is rubbish and learning a better way. I'm not sure what screenshots would be useful in this situation.

Thank you for your understanding and patience.

**Comment by bnmnetp** [comment]
My understanding of what you are reporting as follows:

You have an assignment that has both Readings and Problems.

In the Readings section you have selected the Exercises sub chapter and set the threshold to 5 

In the Problems section you have selected some specific problems from the Exercises chapter that you want the students to do.  How have you set the autograde and which-to-grade fields for these problems?

Let me try to clarify a couple things:

In the Readings section when an activecode problem is selected the grading method is simply "Did the student Interact with the code in any way.  Run it? Change it?"  If so, then give them the credit for the interaction.

In the Problem section you have to be more careful about how you set autograde:

* Manual - this is probably obvious that setting it to manual means you have to grade it yourself.
* All or nothing - **IF** there are unit tests written for the question then the student only gets the points if all of the tests pass.
* % correct **IF** there are unit tests written for the question then the student gets points based on the percentage of unit tests that their code passes.
* Interaction - points are assigned just like in the Readings section.  Any interaction will give them the points.

I emphasized **IF** for the two above because not all problems have unit tests.  If you specify % correct for a question that has no unittests then the grade will be a zero.  This is what I suspect is happening in your case.

You might rightly wonder how to tell whether a particular problem in the excercises is automatically testable or not.  Unfortunately right now you need to look at the code or simply try to run a simple solution yourself.  If it has unittests that will be obvious when you click Run.

**Comment by MrShaunMcG** [comment]
Hi,

How do I know **IF** there are unit tests for each question? When I click run on most questions/exercises, an output is given, I would expect this to be the unit test the AutoGrader refers to? The first screenshot shows the assignment creation page. I've set ch3ex4q to %correct and ch3ex3q to All or nothing,  run the autoGrader and a few issues arise...
1. the autoGrader "appears" not to have worked, as the answer the student gave is correct to the question asked.
2. How do I tell if there is a unit test for this particular question? (my original question)
3. When I'm forced to manually mark each question, the questions/answer(s) are not available on the grading screen.
4. Am I doing this correctly :/ ?

In an email exchange a while ago, you mentioned that the autoGrader is working in hundreds of school that use your Book. That's great and I am trying to persevere in my understanding of how the grader works. If, at this point, I am required to manually grade the questions, I don't mind but it seems nonsensical to do that if there **IS** infact an autoGrade feature. I have watched your tutorial videos a number of times and re-created assignments and courses so I get this right. However, the interface doesn't appear to act in the way described on the tutorial videos. I apologize if this is headache for you.

<img width="1289" alt="screenshot 2018-12-03 12 28 49" src="https://user-images.githubusercontent.com/33232546/49373751-0e2d3980-f6f7-11e8-93b6-6df8e733195f.png">
<img width="1318" alt="screenshot 2018-12-03 12 28 56" src="https://user-images.githubusercontent.com/33232546/49373756-12f1ed80-f6f7-11e8-845a-751d68c1e764.png">

**Comment by MrShaunMcG** [comment]
Ah, the other thing. "Interaction" works in the auto grader, as in, if they do _something_ they get a mark but that's sort of pointless in understanding their understanding of the questions. Again, happy to be put down on this, just making an observation.

**Comment by bnmnetp** [comment]
@MrShaunMcG everyone has their own ideas and systems for grading.  What you may see as pointless others see as a useful feature.  Building a gradebook or grading system that makes everyone happy is a losing proposition. So we try to aim for flexibility to allow people to do what they want.

I use the interaction feature as a part of reading assignments to get the students to read in a low stakes environment.  I don't want them to be stressed while I doing the reading thinking they must instantly comprehend everything.  In fact if you couple this with the student progress indicator it does give you very useful information about the kinds of things you might want to start your lecture with.  If most students took multiple answers to get the right answer to a question then thats a good indication that the concept is probably confusing or not explained well in the text.

I hear you about how to know if a question has unittests or not.  Not all activecode questions do have unittests and those do need to be manually graded.  If you could add that as a separate issue that would be great, and relatively easy for someone to fix.

**Comment by MrShaunMcG** [comment]
Okay cool! I'm beginning to understand a bit more :) I'll add that as a separate issue and see what pops up. Whilst we're talking, can you tell me how to or show me a link to a tutorial on how to add my own unit tests then? Since I'm going through marking the exercises, I might as well add the tests in as I go, save doing it all again later :)

Thanks Bradley
