### ISSUE TITLE
6-10-6: What will the following code draw?

### ISSUE THREAD

**Issue by evelynzayas** [RunestoneInteractive/RunestoneServer#1090]
On this page,
https://runestone.academy/runestone/static/StudentCSP/CSPNameNames/exam5a6.html

6-10-6: What will the following code draw?  

produces a straight line, so none of the 4 answers are correct.

**Comment by bnmnetp** [comment]
Interesting point.  Clearly that is not the intent of the question.  If you think through what the function shape is supposed to draw you would definitely not conclude a straight line.

The problem is that the `from turtle import *` line is misplaced and the shape function from the turtle module is replacing the shape function defined in the question.
