### ISSUE TITLE
Commerical model for Runestone

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1113]
Based on a discussion @bnmnetp and I had, I'd like to suggest moving Runestone to charging for access to the instructor interface, while providing free access to ungraded books (those which doesn't have an associated instructor interface). Specifically, I propose two paths to charging for instructor interface access:

1. Student-paid. Instructors may create a new course in which students must pay to enroll in the course; instructors will have free access to the instructor interface in order to assign problems, grade them, etc. This is the typical university textbook model.
1. Institution-paid: Instructors may create a new course when their institution pays a fee for a set number of students. This is the typical K-12 textbook model.

All Runestone source code will remain open-source, licensed under a GPL (or similar) license. If someone wants to host their own site without charging students or instructors a fee, they're free to do so. If the host wants to charge a fee, they must pay Runestone a licensing fee.

# Funding model
All payments are made on a per-course basis. That is, an instructor would create a course with a start and an end date. Students then enroll in this course between the start and end date. A payment by the institution or students happens as a part of this process. Students will then have perpetual access to the course. Because students enroll in a specific, limited-time course, this would prevent the most common forms of avoiding payment: a student can't resell the userid/password, because that course expires at the end of the semester.

# Implementation
I therefore would like to:
- [ ] Add an `end_date` field to the `courses` table. The maximum allowable time between start and end dates will be 4 months.
- [ ] Add a `student_price` and an `instructor_price` field the `courses` table. A price of 0 or less means free.
- [ ] Add a new table, `payments`, which contains an `auth_user.id` and a `courses.id` to identify the purchaser, plus any data need for the purchase (a Stripe token, etc.)
- [ ] After a student adds a course, direct them to a payment page if the `student_price > 0`.
- [ ] After instructors create a new course, direct them to a payment page if the `instructor_price > 0`.

@presnick, I'd appreciate your feedback on this.

**Comment by bnmnetp** [comment]
@bjones1 thanks for writing this up and getting it out here for discussion.

My high level goals and constraints for finding a business model are:

1.  Make Runestone Sustainable
2. Encourage growth and new contributions of content as well as infrastructure
3. Continue to allow free and open access to all the content
4. Build the Runestone business so that we can provide good support for instructors

There are lots of ways that these goals might be achieved but I think this proposal is a good starting place for discussion and I hope to hear from a lot of people.

**Comment by conzty01** [comment]
I like where the model is going by keeping basic access to textbooks free while also charging for more premium features. I might suggest that the maximum course length be a little bit larger in case schools, specifically K-12 schools, need to extend their academic calendar due to inclement weather such as snow-days, heat-days, or hurricane days.

In my area for example, the 2nd semester begins in January and if there are a few snow-days in the winter months, then the academic year can extend into June. It is feasible to imagine that an instructor knowing that this might happen could and would prepare material outside of Runestone in case their academic calendar exceeds the maximum course length, but it is food for thought. Perhaps courses could have a different maximum length for the university model vs the K-12 model and different prices depending on the length of the course?

**Comment by bjones1** [comment]
Good point -- it would make sense to base semester length on the institution.

**Comment by bjones1** [comment]
Some additional thoughts on this, specifically on implementation. Feedback is welcome!

The existing register page should be divided into three pages:
- A registration page that allows users to create a userid/password, but nothing else. This makes the form less frustrating: there's less information to be validated, and therefore less to get wrong and be forced to re-type.
- Next, send users to an add course page. It would look more like the registration page (no carousel of changing images about Runestone), but would only have a course name to enter. (The add courses link would go here, instead of to the existing profile page.) It would also have an option for instructions to create the course.
- Finally, depending on the price of the course, send users to a payment page or to a donation page.

Changes the complement this:
- The profile page would not allow adding a course, or defining a section.

**Comment by bjones1** [comment]
Closing this, since there's not a lot of interest.
