### ISSUE TITLE
Practice Interface

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1130]
Todo list for making spaced practice ready for production:

1. Implement stuff discussed in the comments below.
2. Update other books with :practice:

**Comment by bnmnetp** [comment]
The big issue is really around 5.  

1.  Should practice look like any other assignment and should instructors have control over the granularity of the practice problems through the assignment interface?  
* In this case the selection process is similar to the reading and exercise selection so it would be quite natural.
* On the negative side I think there is already plenty of complexity for instructors to understand in the assignment builder and adding one more kind of thing to add to an assignment may be too much.

2.  Keep practice as a separate idea but display it in the gradebook.
* In this case the Practice tab will allow the instructor to configure how many days of practice and how many points each day is worth
* this is much simpler and I think fits the spaced repetition model a bit better.

The big question is how and when do we calculate the points for the practice stuff?
* If we follow option two then we could add another calculation for the gradebook that uses the existing practice completion mechanism.

**Comment by presnick** [comment]
Let's go with option 2. Here's a list of things that I think need to be done, along with proposed assignments of people to them:
1) In the practice tab, instructor can configure the following (@ImanYZ to implement these additions):
  - end_date for the practice
  - max number of days of practice students can get points for?
  - how many points for completing each day?
  - how many items to get the point for that day?
  - whether creation of topic flashcards is:
     - self-paced (when student opens a page)
     - whenever a page is assigned in any reading assignment and the reading assignment deadline passes
     - manually by the instructor, as it is implemented currently.

2) Write practice into the assignments table as row id 1. This should happen as part of initdb. @presnick to implement.

3) When processing a student answer to a flashcard, compute grade (borrow code currently used for showing status on each page) and write grade to assignment grades table, and send via LTI if there is a callback GUID for it. When showing  the flashcard page, present current state of grade rather than calculating. @presnick to implement.

4) In assignments page controller, check for id=1 and redirect to practice page. Remove special case redirection in the lti controller. @presnick to implement.

5) If self-paced, when student marks a page complete, create the flashcard for it. @ImanYZ to implement.

6) Nightly scheduled task to create flash cards for reading assignments that have ended but for which cards haven't been created yet. @bnmnetp to implement.

**Comment by ImanYZ** [comment]
We also need to fix the practice tool issues with the timezone.

**Comment by ImanYZ** [comment]
If the practice setting is not set up yet and a student tries to practice, we should show them a message to encourage them to ask their instructor to set up the practice setting.

**Comment by presnick** [comment]
I have completed #3 in the comment above. @ImanYZ please get it from my branch practice_feature.

**Comment by ImanYZ** [comment]
I completed: https://github.com/RunestoneInteractive/RunestoneServer/issues/1130#issuecomment-415458973

**Comment by ImanYZ** [comment]
I also changed `_get_qualified_questions` in `assignments.py` and `_get_toc_and_questions` in `admin.py` so that it also takes questions with no `topic` tag. However, I still believe all questions should have their `topic` specified.

**Comment by ImanYZ** [comment]
I completed this thread.
