### ISSUE TITLE
Resolve timezone issues in practice feature

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#1135]
Principles:
- all timestamps stored in DB are UTC, with separate field for local tz offset
  - get local tz offset from session.timezoneoffset
- two dates are relative to user's local time:
  - user_topic_practice_Completion.practice_completion_date
  - user_topic_practice.next_eligible_date   
- all computations in python are using UTC times, never timezone aware times
  - except when setting or comparing one of the two dates:
     - to set practice_completion_date, get utcnow and do a timedelta of user timezoneoffset and take .date()
     - to get today's local date, for filtering eligible flaschards, in controllers/assignments/practice() or elsewhere:
```today = (datetime.datetime.utcnow() + datetime.timedelta(user_timezone_offset)).date()```

```>>> w = datetime.datetime.utcnow()
>>> w
datetime.datetime(2018, 8, 22, 16, 14, 23, 650236)
>>> q = w + datetime.timedelta(hours=12)
>>> q.date()
datetime.date(2018, 8, 23)
```

**Comment by ImanYZ** [comment]
Done.

**Comment by bnmnetp** [comment]
@presnick I also added timezoneoffset to every hsblog and runlog api call.  There are places where we can end up without a timezone offset in the session.  The main place is when an instructor has to re-login from the instructor interface, or when a student is forced to re-login from assignment page or practice interface.  In that case the usual place to set the timezoneoffset was bypassed.

**Comment by bnmnetp** [comment]
We should also deal with the time zone offset in minutes.  I just got a server crash due to the fact that the time zone offset was -5.5 and we try to convert it to an even number of hours.  But as I learned when I visited Australia there are some time zones that are on a 15 minute or 30 minute difference!

So that will also require a change in the components.  That's where the trouble starts.  Javascript actually does the right thing and gives us the offset in minutes but I divided by 60.
