### ISSUE TITLE
Timestamp on assignments based on client device datetime

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1185]
A clever student confessed to me that he was able to change the date/time of his PC to submit late assignments.

I confirmed that I can change my laptop's date 9/4/18 and run/save an assignment. The date on the assignment is 9/4/18.

It would be nice to use the server's date/time stamp to avoid this workaround.

**Comment by bnmnetp** [comment]
Can you give me more specifics?  I can't think of a case where I use the browsers time instead of the servers time.

**Comment by psmaker** [comment]
Hmm... Maybe it is OK...

I just tried it again. I changed the date to 1/1/19 on the first exercise in Chapter 2. I see the date of 1/1/19 on the history scrubber.

But, when I refresh the entire page and press the 'Load History' button, then I see today's date of 1/9/2019.

So, looks like the it is OK. I was mistaken (and so was the student who thought he had a workaround.)

I'll close this.

**Comment by bnmnetp** [comment]
OK, cool.

I did check and I don't even send a timestamp when recording answers or code runs.

But, the history slide will always add the most recent run to the far right,  I suppose that could be changed so it was inserted at the correct timestamp but I'm not sure its worth the effort.  Since when you reload the page, then it retrieves them in the order of the timestamps stored in the database anyway.

Also, when the autograder runs it looks at the database timestamp.
