### ISSUE TITLE
Can't create custom link

### ISSUE THREAD

**Issue by ksteph** [RunestoneInteractive/RunestoneServer#1299]
**What Course are you in**
I'm using https://runestone.academy/runestone/books/published/thinkcspy/index.html but tried to create a new course called DukeCS101FA19

**What Page were you on**
Main page

**What is your username**
ksm

**Describe the bug**
I went through the create a course page to create a new textbook for this semester's course like usual, updating the project name to DukeCS101FA19, when I click create the link looks to be the default link to thinkcspy rather than my project name:
https://runestone.academy/runestone/books/published/thinkcspy/index.html

**Traceback**
na

**Additional context**
na

**Comment by bnmnetp** [comment]
Yes, but the page banner should say DukeCS101FA19

This is based on the course you to which you are logged in.  We changed the architecture this summer so rather than building a static site for every course (a support nightmare!) we now dynamically serve each course based on the "base course"

This actually has a huge benefit of keeping students from accidentally landing on the base course and doing their work instead of your course.

**Comment by ksteph** [comment]
Ah, my apologies, I didn't know that was changed.

**Comment by bnmnetp** [comment]
Its fine. We have made many changes this summer.  You may want to take a look at our blog to see some of the other goodies.  http://runestoneinteractive.org
