### ISSUE TITLE
Multiple choice question mistake

### ISSUE THREAD

**Issue by agrayburn** [RunestoneInteractive/RunestoneServer#1346]
**What Course are you in**
CSAwesome

**What Page were you on**
Section 2.2
**What is your username**
agrayburn@fortcherry.org

**Describe the bug**
Question 2-2-2 (I believe) which is about the Gregorian Calendar object... shouldn't the month be 8? Since the months start with 0?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
Good catch! Actually that question is asking about a made-up Date class instead of GregorianCalendar, but I didn't tell you whether months are numbered from 0 or 1, and I should! I changed it to say "and assuming that months in the Data class are numbered starting at 1" to keep the question more about the constructor argument order instead of a trick for the month. Thanks for reporting it!

**Comment by agrayburn** [comment]
Happy to help. Thanks for the prompt attention! Btw, I love this resource!
