### ISSUE TITLE
Preview question does not properly resolve when using a WSGI virtualenv

### ISSUE THREAD

**Issue by cbondurant** [RunestoneInteractive/RunestoneServer#1351]
**Describe the bug**
When attempting to build a preview of a question, runestone is unable, returning the following error to the page
`Error: Runestone build failed: /usr/bin/python3: No module named runestone `
This error seems to stem from the fact that I am using a WSGI virtualenvironment, so the python context that is running the web2py request is not the same as the subprocess that is called in
`controllers.ajax.preview_question`. The `/usr/bin/python3` context does not have any runestone files installed as they are instead installed within the virtual environment for containment reasons. 

**Additional context**
I am using `mod_wsgi` under apache2, specifying the virtual environment through `WSGIPythonHome <path-to-venv>` on the sites-available config file.

**Comment by bnmnetp** [comment]
This is a good catch.  In other places we have used the equivalent of `python -m  runestone`  instead of running Runestone directly.  Also because running in a uwsgi container can cause problems we added `settings.python_interpreter = sys.executable` to 0.py. You can use settings.python_interpreter as the correct value for python.  The value can be set to your virtual environment as needed in models/1.py
