### ISSUE TITLE
Changed points value not being updated on Grade page

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/RunestoneServer#1393]
**What Course are you in**
adrian_ac101f19

**What Page were you on**
https://runestone.academy/runestone/admin/grading

**What is your username**
shill@adrian.edu

**Describe the bug**
I originally set up assignment hill2019-function as having 20 points, but then changed it later to 10 points.  The autograder knows that it is 10 points, but on the grading page it says "Points: 20" at the top of the page, even after a hard reload.
<img width="518" alt="GradingBug" src="https://user-images.githubusercontent.com/5134014/70540662-a395b180-1b33-11ea-9346-17b2f9865994.png">

This isn't a major bug but it is potentially confusing.

**Comment by bnmnetp** [comment]
So, hill2019-function is a question, not an assignment right?  I see that it is used in two assignments, one worth 20 points and another assignment where it is worth 10 points.  One assignment appears to be called Ch 1 and the other appears to be FinalExam

??

**Comment by sahi1l** [comment]
Ah yes that would explain it; I accidentally added it to Ch 1, and while it is worth 10 points in FinalExam, it is worth 20 points in Ch 1.  The grading page is pulling the points total from the first assignment of the list, or something like that.

**Comment by bnmnetp** [comment]
I imagine we must be looking at assignment_questions table and searching for the questionid and course id, but not the assignment id. 😞 I'll look into it.

**Comment by cigas** [comment]
Ditto. I ran into this today as well in course CS152HOSP2020, Virtual Week 2.
These are exercises I've written, and used in previous courses, but I don't think I've used them yet in this course, though I did copy assignments from a previous course, so that may be why there is a mismatch.
User: cigas

![Assignment-score](https://user-images.githubusercontent.com/11619455/78098483-dabef580-73a4-11ea-8f24-f0b62fb997b5.PNG)
![Assignment-score-bad](https://user-images.githubusercontent.com/11619455/78098495-deeb1300-73a4-11ea-8729-25b023d23567.PNG)

**Comment by bnmnetp** [comment]
I am trying to track this down.  The database has the correct number of points for this question in the database.  I'm struggling to figure out why it is being displayed incorrectly in the grading interface.   I'll keep at it.

**Comment by bnmnetp** [comment]
Figured it out... Testing a fix right now.

**Comment by bnmnetp** [comment]
fixed
