### ISSUE TITLE
CSAwesome: Interworking with hypothes.is broken  - have you recently changed CSAwesome URL?

### ISSUE THREAD

**Issue by sjyjj** [RunestoneInteractive/RunestoneServer#1523]
**What Course are you in**
CSAwesome

**What Page were you on**
All pages.

**What is your username**
snam2@msudenver.edu

**Describe the bug**
it's an issue regarding linking CSAwesome with Hypothes.is comments that I have created.  On 9/13 afternoon, I've noticed that all the comments I have created in Hypothesis are not accessible.  From my initial investigation, I conjecture that the CSAwesome book URL has been changed and that may have broken the linkage between two.

OLD: starts with "runestone.academy/..."
New: "csawesome.runestone.academy/...

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
Contacted Hypothes.is help desk and got the following response:

if you're correct and the URL has changed then the site owner needs to establish document equivalence between the old URLs and the new ones. Sorry I don't have a simpler method for you, but if you reach out to the site owners you're welcome to direct them to support@hypothes.is and I can try and answer any questions if the document equivalence article is confusing.

Document Equivalence site URL: https://web.hypothes.is/help/how-to-establish-or-avoid-document-equivalence-in-the-hypothesis-system/

**Comment by bnmnetp** [comment]
Yes we brought on this new server on Saturday.

The traffic this fall became so heavy that we had to bring on a second server.  Given my time constraints and the urgency of getting more resources online I chose to use a simple url redirect for all csawesome users. This was a more workable solution that a load balancer and changing all of our https certificates.  Unfortunately I didn't anticipate what this might do to users of Hypothesis.

If you were logged in to hypothes.is I'm guessing you can still find all of your comments.  Otherwise I'm not sure what we can do.  Happy to take suggestions from anyone who might know more.

Sorry for the inconvenience!

Brad

**Comment by bhoffman0** [comment]
Sorry about this! I don't think we can do the document equivalence meta tags that hypothes.is suggested, because the old urls no longer exist to put a meta tag in them.  

The only immediate plan  I can suggest is to login to hypothes.is and copy your old annotations and re-do them in the new csawesome urls, or do divide and conquer and ask your students to help copy them or to just read them in hypothes.is. 

-Beryl
