### ISSUE TITLE
Sort the assignment list alphabetically, not by Due Date (or give an option)

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1546]
The list of assignments that I have created is sorted by due date in the drop-down selector. It would make more sense to sort it alphabetically.

Thanks!

**Comment by jobartucz** [comment]
Ok, so I don't think it's by due date, but I'm not sure what the sorting method is. Is it alphabetical and I'm not getting it?

Screenshot here: https://imgur.com/a/gBQCkfF

**Comment by bnmnetp** [comment]
I checked the code and it is sorting by due date.  In my opinion it should really be reverse due date so that the most recent assignments are at the top of the list.

**Comment by bjones1** [comment]
I agree re: sort by reverse due date.

**Comment by jobartucz** [comment]
I would agree with "sort by reverse due date" by default, but then I guess my feature request would be to also allow sort by alphabetical or reverse alphabetical. In general I don't really care about the due dates for most assignments, so I just set them to something random way in the future. I can manually go back and make sure they are in order for now, but it would be great to just be able to sort by the name of the assignment 2.01 asdfsad, 2.02 asdfasfd, 2.03 asdfsadf as that seems more intuitive to me (and easier to see in the list itself)

**Comment by bnmnetp** [comment]
I know this seems like a simple request, and to be honest what/how we sort is a small change to the code.  But adding configuration options is not.  IMHO, this is why so many LMS end up being a mess.  Everyone has their way that they want to do things. So LMS that try to be everything to everyone end up with a massive number of options that are hard to figure out and end up making nobody happy.  @jobartucz I'm not picking on you but this is a recurring problem with the LMS side of Runestone, and this seems like a great opportunity to have this discussion.  

I think coming up with a consistent strategy for feature requests like this is important. It is easy to take these one at a time and just keep adding options, but I don't like that path. Its funny how rarely people have feature requests for the contents/design/UI of the textbook side.

As @bjones1 would be the first to point out, every new option adds more complexity.  More paths to test and more code to maintain.

I would like to avoid both problems. 

The LMS part of Runestone has always been opinionated.  Mostly doing things that way that made **me** happy. But that is harder to justify now that I am working on Runestone and not in the classroom.  I like the opinionated approach because it keeps things simpler, The risk is that it makes some people unhappy because it doesn't fit with the way they do things.

I think we need to treat each feature request seriously, and use it as an opportunity to think about the design and usability of the interface. For example, maybe there is a better design for the assignment interface that puts sorting and selecting assignments in the hands of the user without adding a configuration option. We have used the Javascript library `handsontable` in several places and that allows you to sort on whatever column in whatever order makes you happy.  (I'd love to see the gradebook re-done using `handsontable`.)

Brad

**Comment by jobartucz** [comment]
Thanks @bnmnetp . I appreciate the detailed response and did not take it personally. Having worked in software for many years, I understand how dangerous the phrase "could you just" can be :)  . I have never run a large project on GitHub, so I don't know how the issue tracker works, but in the ones I've used it was easy to prioritize and categorize feature requests. "Nice to have" feature requests could always be thrown in a bucket with others of the same type as sub-issues of something larger (like "redo gradebook with `handsontable`"). When that bucket got big enough, the team would go through it, figure out which ones to do and which ones to "maybe do sometime later if at all" and plan them out for a future release.

So I guess what I'm saying is that I've just been dumping all my "nice to have" feature requests in here, not really expecting anything to be done about them, but put on a wish list for some day. The feature requests I've had for content, I've emailed directly to Beryl. 

I don't know what the right way to do this for Runestone is. I agree 100% with your caution as the success of Runestone creates new headaches. I appreciate the work you are doing!
