### ISSUE TITLE
Unexplained error after the end of your code

### ISSUE THREAD

**Issue by JoeHn01** [RunestoneInteractive/RunestoneServer#1553]
CSC-150-MWF-20Fall

yousef.hanafi

This bug happens with every activity I attempt to save and run. I get this obnoxious message that says the following:
"An error occurred after the end of your code. One possible reason is that you have an unclosed parenthesis or string. Another possibility is that there is an error in the hidden test code." For that reason, I cannot work on any activity in the book, which is very frustrating.

Please help me fix this problem because I am falling behind in my class.

**Comment by bnmnetp** [comment]
Sorry you are having this issue. 

All the active codes are working fine for me.  Are any of your classmates having similar problems?  

It may be a browser issue.  What browser are you using? Have you tried using an alternative browser?  Can you send a screen shot of a specific activity or at least the name in parenthesis after the activity number?  Some activities are created by instructors and contributed to the community so it could be an actual error with a particular problem your instructor has assigned.

**Comment by bnmnetp** [comment]
OK, I can see some of the active codes that you are having problems with.  Here is what I am seeing.

<img width="890" alt="Screen Shot 2020-10-23 at 1 59 30 PM" src="https://user-images.githubusercontent.com/51115/97043412-0e778d80-1538-11eb-8eb0-5fc959ad5677.png">

If you cannot switch to a different browser try loading the page in incognito mode.  Or do a hard refresh (https://elod.in/how-to-do-a-hard-refresh-in-every-browser/) and then reload the page.  It looks to me like something is corrupted in your browser.

**Comment by bnmnetp** [comment]
I heard from your prof.   

1.  She says she made you a new username, but that username has never logged in.
2. I can see that you have had several successful runs of code after you reported the problem.  Is it resolved?
3. She tells me that you are the only one having problems, which means it is very likely that you have some plugin or extension installed on your computer that is causing you trouble.  You didn't respond, so I don't know if you are using a different browser or not.

**Comment by JoeHn01** [comment]
Hi, sorry for not responding promptly. I have tried a different browser, updated my Chrome, used a different laptop, and logged in through a school computer, but none of these seem to have made a difference. I do not have the first clue on what originated this issue with me only. Sometimes the code works perfectly normally, but most of the time, it does not. Are there any other thoughts on what could be causing this problem?

**Comment by bnmnetp** [comment]
I don't have a good idea based on what I know.  I am not getting any similar reports from any other classes.
Are you working from home? Do you have a particularly bad/slow internet connection?  Do you have any plugins installed in Chrome such as an ad blocker or something else that may interfere with the normal operations of a page? 


Two things that will give me some more data to go on.

1. The next time you get the error Bring up the Javascript Console (View -> Developer -> Javascript Console) and upload the screenshot of that here.  Hopefully there will be an error message or something to give me a clue.
2.  Your prof made you a different username yousef_hanafi2 I would like you to try using that username to see if the problem returns.  In general I have disallowed usernames that have `.` characters in them as they cause lots of problems for the grading interface.  But I made myself a username with a `.` and I haven't been able to reproduce your problem. Also all of your classmates have `.` characters in their usernames too.   However your's does not have the `@yotes....` part like the rest of them.  Did you register yourself?

**Comment by JoeHn01** [comment]
I do not know what you mean by bringing up the Javascript Console. Could you please elaborate more on that?
Also, I did register myself. Is it possible that registering with a different email address might help solve the problem?

**Comment by bnmnetp** [comment]
When you are in Chrome Click on the View menu, select Developer and then select Javascript Console is what you need to do.

**Comment by JoeHn01** [comment]
Does this screenshot suffice?
![console](https://user-images.githubusercontent.com/73361712/97753766-ebab2300-1abb-11eb-97dd-51844169658a.png)

**Comment by bnmnetp** [comment]
are there any other messages before those that are visible in this screenshot?

**Comment by JoeHn01** [comment]
No, everything I found is included in the screenshot.

**Comment by bnmnetp** [comment]
Your professor made you another username yousef_hanafi2 - I would like you to try logging out and then logging in using that username.

**Comment by JoeHn01** [comment]
I have done that, but there was no difference in running the code.
![image](https://user-images.githubusercontent.com/73361712/97754889-e64ed800-1abd-11eb-9c49-3972f8e286b1.png)

**Comment by bnmnetp** [comment]
OK, that would seem to rule out your particular username.  Which is what I expected.

What version of Chrome are you using?  Are you on Windows or Mac ?

The only thing I can tell from the Javascript console is that you must have some other plugin loaded as the message about new version 11swbtest is not from Runestone.  All of the messages that have VM441:50 at the end of them are not from us.

I'm going to add some additional code this weekend to try to provide more information in the Error message you see in the hope that we will learn enough to figure out what is going on.

**Comment by JoeHn01** [comment]
I'm using Chrome Version 86.0.4240.111 (Official Build) (64-bit), and I am on Windows.

Thank you very much for your help. I hope we can get this sorted out soon.

**Comment by bnmnetp** [comment]
So do I.  I'm doing my best but it is really hard to figure out what is going on when it seems that it is only happening to you.

Would you mind if I reset your password so that I can login as you from my own Chrome browser to see if I can recreate the problem somehow?  I can set the password back to what it is now when I'm done.  I would probably try to do that early tomorrow morning.

**Comment by JoeHn01** [comment]
Absolutely, please do that. Thank you.

**Comment by bnmnetp** [comment]
Well, I've run many many activecode examples using Chrome on my computer logged in as you and every single one has worked without an error.  So what does that tell us?

1. The problems are not related to your username.  We have shown that in two ways now since I don't get errors on my computer when logged in as you.  And you DO get errors when using an alternate username on your own computer.
2. The javascript console screenshots you sent me indicate that you have other software installed in Chrome on your computer. 
3. I don't know if you have some chrome extensions installed such as an ad blocker or other. ??
4. You have said that you have tried to use another browser and even another computer but you still get errors.  which is in conflict with my own testing.

My instincts are that it is some other software you have installed that is causing the problem.  Maybe the code I put in to give more information on the error will help.  Next time this happens check the entire error message and add it here.

In the meantime I would encourage you to try installing Firefox and using that for Runestone.  If you get problems with Firefox you can pull down the tools menu, select web developer and toggle tools in order to see the Javascript console in Firefox, I am curious what error messages we might see there that are different from Chrome.

**Comment by JoeHn01** [comment]
Thank you for your efforts. I have tried Firefox, but it made no difference whatsoever. I have removed all the extensions, including the built-in ones. from Chrome and tried again. I have noticed something new. If the code is 14 lines or above, I get a different message. I have sent a screenshot of it here. I hope it helps.
![image](https://user-images.githubusercontent.com/73361712/97916300-070e6c00-1d10-11eb-9234-1ff15cfa582c.png)
