### ISSUE TITLE
Run/Save does not save their code all the time anymore

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1589]
**What Course are you in**
LHSIntroCS_2020

**What Page were you on**
Any active code window

**What is your username**
lhsadmin

**Describe the bug**
Not really bug, but it seems like the Run/Save behavior has changed. Before, I think it was saving any code that the user typed even if it had a syntax error. Now, it seems to only save code that runs w/o error. It was really nice to have it save all the snapshots of the code as the student was developing it for two reasons.

(1) I can see how much the student worked on the development of the problem. It is useful to catch "cheaters" by seeing the evolution of their code. This gives a little less visibility since syntax errors (which are so normal) are not saved.

(2) Often times a student will tell me they have an error they can't figure out (like a syntax or other error). If it is not saved, then I can't see it on my end in the Grading tab.

(3) The most significant issue is that if a student has an error, but can't figure it out and decides to sleep on it, when they come back to refresh the page, the work is gone. This is quite a significant issue.

**Comment by bnmnetp** [comment]
I agree, I did not intentionally make this change.

I had done a lot of updates to the internals of active codes over the last month or so and this must have been caused by one of those changes.  I've also been testing a lot of fixes this last week and I cannot reproduce this issue on my dev server, so I'm pretty confident that it is fixed.  I'll do a new release on Saturday.
