### ISSUE TITLE
Assignments with unit tests not behaving correctly

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneServer#1607]
**What Course are you in**
CS152HOSP2021

**What Page were you on**
Grading/Assignments/Unit 4: Warm up
Grading/Assignments/Unit 4: Fruitful function practice

**What is your username**
cigas

**Describe the bug**
The immediate manifestation  of the problem is that when grading student programs, I click the Run button and get a message displayed like "failed to find object to record unittest results! percent:100.0:passed:5:failed:0"
The code runs OK and the tests are correct, but that error message is a problem. 

![image](https://user-images.githubusercontent.com/11619455/108777299-351af480-7529-11eb-843d-2334469b05d5.png)

**Additional context**
Both the assignments Week 4 Warm up and Week 4 In Class had issues when I created them. I created Week 4 warm up from scratch using problems I'd written previously in the database. I copied the assignment Unit 4 Fruitful Function Practice from the course CS152HOFA2020.

When I and my students tried to access the questions from the Assignment page, the entire rst document was displayed as written, so students saw the markup and unit test code, but couldn't write their functions. In order to fix this, I had to edit each question in the assignment, Generate/View HTML, then Save Edits. This fixed the display.

Unfortunately, I cannot reproduce this behavior again. I've tried copying several assignments from past terms and everything seems to display correctly now, so I don't know what happened. I had a similar problem earlier in the term, but don't remember all the exact details.

**Comment by bnmnetp** [comment]
I think this was a transitional error.

I made some changes to the components to make them more consistent.  Which meant that I changed the html that runestone generated when building a book.  BUT I completely dropped the ball on questions written in the web interface.

* Questions from the book are automatically rebuilt every saturday when I update and rebuild all the books.
* Questions written in the web interface are only rebuilt, on demand.  That is when you edit and rebuild.

For the future I'm working on a script that I can run when I make a backward incompatible change to the restructuredText so that all of the questions entered in the web interface can have their html updated.

Sorry for the problems, but this change was a long time in coming and makes everything a lot easier to maintain.  Instead of code written by half a dozen different summer students, it is now following modern javascript conventions and written by me. (not necessarily better, but at least consistent 😬 )

**Comment by bhoffman0** [comment]
Hi @bnmnetp, I've run into this problem again in Barb's old course StudentCSP. When I create new problems in that book with unit tests, for example ch4ex1qAutograded, they don't autograde correctly and give the error "failed to find object to record unittest" when run in the Assignment tab. I tried edit and rebuild, and I tried copying them into new problems, with no luck. But if I copy them into a new problem in a CSAwesome book, it works fine. So, I'm thinking it's because the StudentCSP is old and hasn't been rebuilt in a long time, but it does look like you made some changes to its github repo https://github.com/RunestoneInteractive/StudentCSP since 2021, so maybe not. Any ideas?

**Comment by bnmnetp** [comment]
I just rebuilt StudentCSP and it will be live in moments.... Hopefully that fixes it.  If not I will have to go into debugging mode to figure out what is wrong.  StudentCSP was not that far out of date.

**Comment by bhoffman0** [comment]
Unfortunately no. I tried rebuilding the questions again and copied it into a new question with a new id, but it still gives the same error when run in the Grading tab. I'll keep trying things. Here's the console error:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/4571962/189949830-14b6cee1-4a6e-488c-9d60-c2d6b136ec4f.png">

**Comment by bhoffman0** [comment]
Thank you! I think it's working. It didn't work with rebuilding the old ones, but when I copied one into a new blank one in that course, it worked! Great detective work!
