### ISSUE TITLE
CS Principles: Big Ideas in Programming  5.1 Assign a Name to a turtle - images not showing

### ISSUE THREAD

**Issue by mrkirkmwhs** [RunestoneInteractive/RunestoneServer#1612]
Hello,
Looks like some img refs broke with the new configuration.

The text on the page:
//The following program uses a turtle to draw a capital L as shown to the left, <img src=”../_static/TurtleL4.png” width=”150” align=”left” hspace=”10” vspace=”5” /> but the lines are mixed up.//
![51error](https://user-images.githubusercontent.com/40363053/110530191-c40a3e00-80df-11eb-8b3a-953b2f92a17f.png)

**Comment by barbarer** [comment]
This is in the CSP ebook.  I will fix it.

**Comment by bnmnetp** [comment]
The following parsons problems still need to be updated to use the new embedded parsing.


- [ ] 5_1_1_Turtle_L
- [ ] 5_1_2_Turtle_Check
- [ ] 5_3_1_DrawF
- [ ] 5_3_2_DrawA
- [ ] 5_4_2_JandT
- [ ] 10_5_1_turtle-x
- [ ] 10_5_2_turtle-squares
- [ ] 5_2_1_DrawN
- [ ] 5_2_1_DrawZ
- [ ] 5_2_2_Turtle-A
- [ ] 10_3_1_Turtle_Spiro
- [ ] 10_3_2_Turtle_Spiro_Blue_Red
- [ ] 10_1_2_Rectangle
- [ ] 10_4_1_turtle-stamp
- [ ] 10_4_2_turtle-circle
- [ ] 10_2_2_Triangle
- [ ] 5_2_1_Turtle-T
- [ ] 6_4_4_Draw_Squares
- [ ] 5_4_3_JandT2

**Comment by vqum** [comment]
Thanks for finding all these. I can update them.

**Comment by vqum** [comment]
@barbarer

Looks like the following problems still have image embed issues. I did capture these in my PR https://github.com/CSLearning4U/StudentCSP/pull/43 if you would want to merge that instead of going through them again, but I'm not familiar with whether you can selectively merge just these from the PR.

- 6.4. Naming Input ([CSPNameNames/namesInput](https://runestone.academy/runestone/books/published/StudentCSP/CSPNameNames/namesInput.html))	
	- 6_4_4_Draw_Squares
- 10.1. Using Repetition with Turtles ([CSPRepeatTurtles/repeatturtles](https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/repeatturtles.html))	
	- 10_1_2_Rectangle
- 10.2. Teacher Note: Turtle Geometry ([CSPRepeatTurtles/turtleGeom](https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/turtleGeom.html))	
	- 10_2_2_Triangle
- 10.4. Making Patterns within Patterns ([CSPRepeatTurtles/patterns](https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/patterns.html))
	- 10_3_1_Turtle_Spiro
	- 10_3_2_Turtle_Spiro_Blue_Red
- 10.5. The Turtle Stamp Procedure ([CSPRepeatTurtles/stamp](https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/stamp.html))
	- 10_4_1_turtle-stamp
	- 10_4_2_turtle-circle
- 10.6. More Turtle Stamp Practice ([CSPRepeatTurtles/RepeatTurtlesPractice](https://runestone.academy/runestone/books/published/StudentCSP/CSPRepeatTurtles/RepeatTurtlesPractice.html))
	- 10_5_1_turtle-x
	- 10_5_2_turtle-squares
