### ISSUE TITLE
sort official problems in assignments above teacher-provided ones

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1642]
When creating/editing assignments, sort official problems above teacher-provided ones

**Comment by Bekjon777** [comment]
What is the difference between "official problems" and the "teacher-provided" ones?

**Comment by Bekjon777** [comment]
For example, when you add chapter 2 to the assignment before chapter 1, the assignments are sorted in the chosen order. Is this what it means?
![image](https://user-images.githubusercontent.com/57421550/135100378-9353f4dc-30e9-48df-9070-9cfd50a8f3be.png)

**Comment by bnmnetp** [comment]
Instructors can write their own questions through the web interface on the assignment page and add them to the book.  You won't see them in your development environment but on Academy there are over 10,000 questions that have been added by instructors this way.

Those questions have the schoolhouse icon next to them rather than the blue book icon to indicate that they are contributed ("teacher-provided") questions.
