### ISSUE TITLE
 No such file or directory: 'romeo-full.txt'

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1680]
**What Course are you in**
python for everybody

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/dictionaries/advancedtextparsing.html

**What is your username**
josecsolo

**Describe the bug**
When I runned the exercise (see image) gives an error message:  No such file or directory: 'romeo-full.txt'
![image](https://user-images.githubusercontent.com/85453807/123652453-98e16100-d82c-11eb-9cfc-906c228c1f99.png)

**Comment by jose-csolo** [comment]
In the 10:10 page 
https://runestone.academy/runestone/books/published/py4e-int/dictionaries/writecode.html
said: "Below is the romeo3.txt file used in Question 7."

if you search with the tools (upper righthand side ), magnifying glass

![image](https://user-images.githubusercontent.com/85453807/123963425-bb9d8200-d9b2-11eb-90d4-09cf4e08cfa3.png)

the only time that a file called romeo3.txt appears is in the same page (10.10)

![image](https://user-images.githubusercontent.com/85453807/123963110-6c575180-d9b2-11eb-81c0-8e0d99271562.png)

Might be related to the reported error of missing romeo-full.text?

Regards

Jose

**Comment by barbarer** [comment]
This bug has to do with the version of Python.  Most of the file examples are using the translator to JavaScript and running in that.  This example has to run in Python 3 on the server instead of as JavaScript.  The way we include files is different for that. I have updated it, but will have to check again on Saturday when it is live to see if that fixes it.
