### ISSUE TITLE
Mobilecsp not showing as logged in when you first change course

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1741]
I'm not sure of this is a problem but it's odd. When you change course to a mobilcsp course it does not show you as logged in even though you are. If you click on a page, it's fine. Other courses show you as logged in. Did we mess up something in config?
I tried on both servers.
<img width="1266" alt="Screen Shot 2021-08-14 at 8 29 41 AM" src="https://user-images.githubusercontent.com/4571962/129449488-a6f42e8c-8a6d-4bf7-9dd8-5a55f9c8e18d.png">

**Comment by bnmnetp** [comment]
Are you seeing anything in the javascript console?  There must be something failing before we fill in that value in the menu... Is the username in the footer?  I'm guessing not.

**Comment by bhoffman0** [comment]
Not in the footer, but it's fine once you click on a page. Some errors:
![image](https://user-images.githubusercontent.com/4571962/129456315-1236f288-5c3f-4749-94c1-acd5d89c6c48.png)

**Comment by bnmnetp** [comment]
I think it is because you are using the raw directive in index.rst that is including jquery and jquery-ui which is somehow conflicting with the jquery that we are including in the runestone.bundle.js. 

Not sure why you are needing to do that, but it may take some experimenting to get everything to play nice. 😊.

**Comment by bhoffman0** [comment]
Oh that makes sense. We don't need those. I took them out of the scraped files but they must have crept back in on some, thanks!
