### ISSUE TITLE
Modifying a grade from grade book drill-down does not update totals

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1763]
From the grade book drill down into an assignment and question.  
Update the grade for that questions.

Going back to the grade book you will see that the overall grade is not updated.

When updating a grade from the drill-down panel, the total for the assignment should be updated. `do_update_total` should be called after the new grade is entered.

**Comment by areskeldi** [comment]
@sreynit02 and I, Berea College students, are working on this issue

**Comment by sreynit02** [comment]
@bnmnetp Which type of questions didn't update the total? We're having trouble recreating this issue.

**Comment by bnmnetp** [comment]
All types of questions.

Make sure you are repeating this by going through the **gradebook** NOT the grading tab.

**Comment by sreynit02** [comment]
Hello, It seems like `do_update_total` is not a function in RunestoneServer, but we found a function in rs_grading.py named `do_calculate_totals` that seem to compute the total score a student earns for an assignment. Did you mean this function? 

Also, if that's the case, we are not sure where to call this function because the gradebook gets data from grades() in dashboard.py which already has a logic that recalculates the total point using another function calls `update_total_points` .
