### ISSUE TITLE
File downloads are working incorrectly (downloading as .json and .html files instead of the actual files)

### ISSUE THREAD

**Issue by lslavice** [RunestoneInteractive/RunestoneServer#1851]
**What Course are you in**
`engr101umich-w22`
(this issue is also affecting `engr101umich-f21`, and that course didn't have this issue before the server change)

**What Page were you on**
1.1. Introduction to MATLAB

**What is your username**
lslavice

**Describe the bug**
When I download these linked files:

* `FuelCalculatorBuggy1.m`
* `FuelCalculatorBuggy2.m`
* `FuelCalculatorBuggy3m`

they download as `.html` files. The code is there, but they used to download as the actual `.m` files, not with `.html` appended. 

When I download `AnnArborTempsAug2019.mat`, the file downloads as a `.json` file that has only this in it: 

`{"detail":{}}`

instead of the MATLAB `.mat` file. Whatever is going on is affecting file downloads in other chapters of the `engr101umich` book. Our semester has already started and we need this resolved soon, please.

**Comment by bnmnetp** [comment]
Downloading an arbitrary file is not even a feature of Runestone.  I have no idea how you set this up to work.

**Comment by lslavice** [comment]
Hmmm... I will ask James and the other Laura about this too, then

**Comment by bnmnetp** [comment]
OK, I think I see the problem...   I guess long ago I must have done a little hack to the nginx server configuration on runestone.  -- nobody other than me could have edited said file.  I added `_downloads` to a regular expression of static files that nginx should just deal with and not bother anyone else about.  I have no memory of James asking or me doing. But there it is.

I'm testing a solution that will be documented, part of the code, and not use a regular expression 🤣 

Should be good by tomorrow.

**Comment by jamesjuett** [comment]
Is the issue that the `:download:` role isn't getting rendered the same was it was before? I'm not sure it ever went to `_downloads` - in the source the intent is for it to go to something like e.g. `https://runestone.academy/ns/books/published/engr101umich-w22/_static/functions_and_data/daily_samples.csv` (which still works).

Or, I suppose it's possible it always rendered to `_downloads` rather than `_static` like that and I just hadn't looked to see it. But, we definitely didn't have a solution that depended on `_downloads` specifically - way back then I just worked it out that it was a link to the right file in `_static`.

**Comment by bnmnetp** [comment]
Anything in `_static` would just work, but the examples for the intro to Matlab section that Laura referenced were pointing at `_downloads`

maybe it wasn't much of an issue since the `.m` files were small and could be just as easily copy/pasted without downloading.

In any case `_downloads` will be supported starting tomorrow.

**Comment by jamesjuett** [comment]
Ah, I just actually read some of the Sphinx documentation for the `:download:` role and saw that it does actually point them to an `_downloads` directory, copying over the original files. So, it must have just happened to work! (At least, I definitely don't remember requesting `_downloads` either! Maybe someone else once upon a time was also using `:download:` and thus requested it.)

**Comment by bnmnetp** [comment]
or maybe someone reported that it was broken and I saw a quick hack to fix it.  At least now it is in the code and documented there to support the `:download:` role.

**Comment by lslavice** [comment]
Thank you both for your quick responses! I'll check tomorrow, and hopefully we'll be back up and fully running. :)

**Comment by bnmnetp** [comment]
fixed
