### ISSUE TITLE
assignment link not working

### ISSUE THREAD

**Issue by vlavergne** [RunestoneInteractive/RunestoneServer#1880]
I'm trying to use the LTI Integration for my personal version of the CSAwesome course.  When students follow the link (which worked like a charm before break, before the upgrade), they are now getting a screen with lots of error messages.  It starts with "Not logged in due to the following errors", and then there's lots of stuff.

The student is able to navigate directly to my personal CSAwesome page.  IT's just that when they follow my LTI integration link (posted into Canvas) that they are getting this error.

Please help!
Thanks

**Comment by bnmnetp** [comment]
Yes, lots of things changed with the upgrade.  But we have the LTI issues fixed.  So that "lots of stuff" would actually be valuable to help figure out what might be happening for your students.

A couple of quick things.

1.  Make sure you are using the new link -- NO csawesome as part of the URL
2. Have your students log out, clear their browsing history and log in again through canvas..  If you made links in canvas before the break you will need to update them.

**Comment by bnmnetp** [comment]
The link for this assignment should be:

https://runestone.academy/runestone/lti?assignment_id=72319

The csawesome server is gone, replaced by a much more scalable set of servers for all Runestone courses.

See:  https://runestoneinteractive.org/2021/12/21/academy_downtime.html
