### ISSUE TITLE
Logged in but can't access class

### ISSUE THREAD

**Issue by Mrs-Simms** [RunestoneInteractive/RunestoneServer#1884]
Myself and a student log into Runestone, when we click to move anywhere on the site  for example if I click an assignment it brings me to the attached page
![Screenshot (90)](https://user-images.githubusercontent.com/34074786/151042594-edbc64d8-4a96-488d-b26b-8d7c81e913db.png)
e

**Comment by bnmnetp** [comment]
Please logout, clear your browsing history and log in again.  This has been reported many times since we did the server upgrade, and this seems to clear up the problem for everyone.

**Comment by bnmnetp** [comment]
Also please make sure that you are just using https://runestone.academy and make sure that you are using the new style links to access your course https://runestone.academy/ns/books/published/YOUCLASSNAME/index.html

**Comment by Mrs-Simms** [comment]
The problem just started happening today.  Thank you. We logged out and the problem was corrected

Mary Simms
Computer Science
Girls Who Code / Web Team Sponsor
Blake HS
240-740-1400

https://tinyurl.com/bhscodes

From: Bradley Miller ***@***.***>
Sent: Tuesday, January 25, 2022 2:22 PM
To: RunestoneInteractive/RunestoneServer ***@***.***>
Cc: Mrs-Simms ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [RunestoneInteractive/RunestoneServer] Logged in but can't access class (Issue #1884)


Also please make sure that you are just using https://runestone.academy<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Frunestone.academy%2F&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u31ReBIjAuw8V1FY%2FYCPKKHQsBmklo4YBGNTD9OdY0s%3D&reserved=0> and make sure that you are using the new style links to access your course https://runestone.academy/ns/books/published/YOUCLASSNAME/index.html<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Frunestone.academy%2Fns%2Fbooks%2Fpublished%2FYOUCLASSNAME%2Findex.html&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DDNTGWjvgenzfpyaoLXD1z1qnrlexY6dgwJw%2F4x%2B7Ls%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRunestoneInteractive%2FRunestoneServer%2Fissues%2F1884%23issuecomment-1021527876&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7Spg2lwi3RFQ%2BlsdkPcNu0C79QksCCAs74Uoa%2FxwztA%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAID7BIRQNVTYIOFKUDGG2ETUX3Z6FANCNFSM5MZDDIUQ&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bBRd77qxDKWW4wHYKFE62vrNwv6XncdkA4%2B3YurnVEk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UZXeii0sJHRwrG7dsRIs9ChwblJsGB0AW4z%2FbAogbbY%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMary_C_Simms%40mcpsmd.org%7C22a521037524466baff208d9e037ff3a%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C1%7C1%7C637787353373495682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Eoa133C9y4BwNgsqm50ErNg4BSPSpdEhZ2%2FEJRBKaN4%3D&reserved=0>.

**Comment by mburns1074** [comment]
I done everything that has been suggested and it has not cleared up the problem for me.  
username: MBurns
Class: APCSA21-22Burns

**Comment by bnmnetp** [comment]
@mburns1074  - What happens ???

I can see that many students in your class are running their code and answering questions today.  Without SPECIFIC information it is impossible for me to diagnose what may be wrong in your particular case.

**Comment by bnmnetp** [comment]
Just to provide some additional clarity on this issue:

### What is going on? The technical details!

With the new Runestone Architecture (See: https://blog.runestone.academy/2021/12/21/academy_downtime.html) We have two separate servers, both of which need to know that a user is logged in successfully.

1. The old web2py based server which is now primarily for logging in and the instructor interface.
2. The new FastAPI based server which is primarily for serving books.

So we had to devise a way for users to login on web2py but also let the new server know that you are legit.  We do this with a secure access token.  That token is only generated when you log in.  However, since some users have not needed to log in since the change was made they are logged in to web2py but do not have the secure access token to view their books.  Hence the re-login.

I didn't really anticipate the magnitude of the confusion this would create.  So in hindsight I could have done a much better job of creating some additional UI that would have caught and explained this problem. I have already made some improvements to this and will launch them Saturday Feb 5.

### Some Important Things to Remember

1. ALWAYS use `https://runestone.academy`
2. ALWAYS use the new style URLs. `https://runestone.academy/ns/books/published/YOURCOURSENAME/index.html`
3. When in doubt, just log out.  Then log in again.
4. Do NOT block Cookies from Runestone we use them for keeping you logged in.

### If you are seeing ads

IF you are seeing ads then you are NOT logged in!  We only show ads to people that have not created an account.  This is not because we want to collect information about you it is because a significant portion of our traffic is "one visit" traffic from search engines.  One of the ways that we try to support this service is by showing ads to search engine traffic.

**Comment by bnmnetp** [comment]
This problem and related problems of student work not getting saved was solved about 10 days ago.
