### ISSUE TITLE
Account deleted

### ISSUE THREAD

**Issue by scruffydogdan** [RunestoneInteractive/RunestoneServer#1894]
I am unable to login today. I am concerned my account was deleted. I tried the pw recovery/username recovery and both indicated that my account didn't exist. Please assist.
Thank you,

Dan

**Comment by bnmnetp** [comment]
Are you a part of a coursera course?  If so, then this is the wrong place and wrong server.

If not, you are going to have to at least tell me a little more information about who you are otherwise I have absolutely no way to figure out what your account should be.

The only way an account can be deleted from the database is if you go through the Profile page and click the box and confirm the warning that your account will be removed with no way to recover it.  So account accidental account deletion is pretty unlikely.
