### ISSUE TITLE
Output variance a bit ambiguous

### ISSUE THREAD

**Issue by FIOpwK** [RunestoneInteractive/RunestoneServer#1895]
**What Course are you in**
java4python

**What Page were you on**
1.5  Java Data Types

**What is your username**
llanhmod

**Describe the bug**
While working on `Activity: 1.5.1.1 ActiveCode (tcpython)`, I noticed the result calculated for celsius is different from the result I see locally in my python repl.  The Activity repl produces C= (21.666666666666667) as the result for F=71. While locally, this same code used in the Activity repl produces (21.666666666666668) .    It would help to have some hint about this variance. 

Here is the code

```python
def main():
    fahr = int(input("Enter the temperature in F: "))
    cel = (fahr - 32) * 5.0/9.0
    print("the temperature in C is: ", cel)

main()
```

**Comment by FIOpwK** [comment]
So, I just leaned about the JS library using its own implementation of the JS Number type.  This doesn't seem like a bug, rather a implementation detail that can be explained.  I don't know if changing the toPrecision() value would show expected results. This can either be closed on someone can comment about any actions.

**Comment by bnmnetp** [comment]
Thanks, I'm not sure how stable some of these differences are.  We could probably add some text that explains that you may see some small differences due to how different systems represent numbers.  I would not get into that for this example in an intro book, but since this book assumes you already know some programming it could be appropriate.

**Comment by FIOpwK** [comment]
The Java repl seems to be stable. It returns 21.666666666666668.
