### ISSUE TITLE
Autograding sometimes giving 200% as scores

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1897]
A teacher reported that since the big server updates, she's noticed some students getting more than 100% in autograding assignments.   For example, for the student with the user name minche262 in the course WHS-2021-P3.  Here are some screenshots. Below this one is 5 points, but he got 9 points in autograding.

![image](https://user-images.githubusercontent.com/4571962/154698761-f5e90ef4-79b1-406b-bb01-acf05043b7c9.png)
Below this one is 5 points, but he got 10 points...
![image (1)](https://user-images.githubusercontent.com/4571962/154698872-2ad0407f-5fd4-4909-9cf2-b12f41444da5.png)
And 200% in the gradebook:
![image (2)](https://user-images.githubusercontent.com/4571962/154698943-a7ddee59-d6f7-4118-8f63-6a1349ce8ebe.png)

I was not able to duplicate this, and I can't think what could be causing it.

**Comment by bnmnetp** [comment]
I'm writing this as I investigate, so excuse the stream of consciousness like narrative...

I can see that in the database there are two rows for minche262 in the question_grades table.  The two rows have indexes just one apart meaning they were inserted one after the other, one has a deadline and one does not.

My first inclination is that this was some kind of database hicup.  Especially since I haven't had other reports of grading irregularities, and I have not been able to reproduce it either.  We use a built in function of web2py called insert_or_update to add a row to this table, so it could be a bug in the web2py database code that is causing this.

In fact it looks like I may have lost a constraint in the database migration that was ensuring this uniqueness. I need to do a little more investigating before I am confident.

**Comment by bnmnetp** [comment]
OK, fun fact - 0.007% of the question grades were duplicates, all recent (since the db upgrade) Thats a pretty good sign that I lost a constraint.   I have:

1. removed the duplicate entries.
2. added a constraint to keep duplicates from happening.

Instructors will need to re-run the autograder -- just to update the totals -- for any assignment where they had this happen.

I'm pretty confident this will fix the reported issue.  And the tiny percentage also explains why it has not been reported by others.

**Comment by bhoffman0** [comment]
Thank you! Impressive bug finding!  I'll let the teacher know.

**Comment by bhoffman0** [comment]
The teacher confirmed that this fixed the problem for her assignments! Thank you!
