### ISSUE TITLE
Active Code not working

### ISSUE THREAD

**Issue by mattiem99** [RunestoneInteractive/RunestoneServer#1903]
I am using the think cspy textbook and the activecode tool is not working. Its just a yellow box with a blue line through it and I cannot interact with it. How do i fix this?

**Comment by bnmnetp** [comment]
The page is waiting for the javascript to load.  Normally this is less than a second.  So you may have some browser issue or maybe you are blocking javascript?  

Please note that the template for reporting problems is there for a reason, which is to help gather enough information to help you.  I can't help you because activecode is working fine for 1000's of people, just not you, but you haven't told me anything I can use to debug the problem.
