### ISSUE TITLE
I am pretty sure it is not saving students work again. I will have them clear their cache. But this is a bug that is difficult to deal with because it crops up when I am trying to grade and I have no record what exactly they accomplished. It is also bad for moral because they loose their work  at least temporarily and since I am not exactly sure what they accomplished we end up using a lot time in class in confusion.

### ISSUE THREAD

**Issue by psuci** [RunestoneInteractive/RunestoneServer#1928]

**Comment by bnmnetp** [comment]
It seems that you are quite frustrated, but this doesn't help anyone figure out what is going on.

I have not made any changes to the server in over a month, and I'm not seeing anything in my analytics that indicates this problem has returned.  Nor have I had problem reports from other instructors.

In order to do anything about this I need to have some specific information.  That is why there is a template for filing a bug that asks you to provided detailed information.
