### ISSUE TITLE
Automatic Course Name Creation - semester is not correct

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#2027]
I understand the desire for automatic name creation, but there are two issues:

1. I just tried to create my spring semester courses and it automatically calls them XXX_fall22
2. Although I teach at Rochester Community and Technical College, I would much rather be able to enter a shorter nickname, like RCTC or RCTC_MN (i.e. include state name)

**Comment by bnmnetp** [comment]
You are not required to accept the suggested name.  You can make it whatever you want it is editable and only a suggestion to help people make sensible names.

Although I would like to get to a point where the student registers with their institution and we show them the names of the courses that are available for their school where they just select it rather than typing it.  In that case the length wouldn't matter right?  Of course it may be crazy of me to think we can make that work as every school will have multiple possible names and nicknames and shortenings.   Fuzzy search....
