### ISSUE TITLE
Question: coding style in the book: spaces around operators and between parameters

### ISSUE THREAD

**Issue by VictorNorman** [RunestoneInteractive/RunestoneServer#403]
In my class, I am a stickler for writing beautiful (or as I call it "hospitable") code.  One thing I try to emphasize is spacing -- uses spaces to make code as easily readable as possible.

One thing that bugs me about a lot of textbooks is that they write code like they are trying to save disk space, but removing as many spaces from the code as possible.  Here is an example, from this textbook:

 return Fraction(newnum//common,newden//common)

This line of code is so much more readable with some spaces in it:

 return Fraction(newnum // common, newden // common)

Also, putting spaces around operators follows (generally) PEP-8's recommendations on how to write python code.

Similarly, there should be spaces in parameter and argument lists, so that readers can more easily see how many parameters/arguments are being declared/passed:

 def **init**(self,top,bottom):

should be

def **init**(self, top, bottom):    # much more readable.

If I submitted changes to the textbook to make these changes, would they be accepted?  It is going to take a bit of work to go through all the code in the book, but I can do it while watching old reruns of StarTrek:TNG on Netflix.  But, I don't want to do it if you consider it to be too much of a stylistic thing.

Thanks.

Vic

**Comment by akulakov** [comment]
No, I would not agree. More to the point, PEP8 and python community does not agree -- PEP8 doesn't say anything about squishing things to fit into one line, but it does say spaces need to be added after the comma and surrounding operators: x, y rather than x,y and x / y rather than x/y.

**Comment by bnmnetp** [comment]
Its fine to be an advocate for PEP8 conformity, but please don't lose site of the big picture and the audience of the textbook.  Namely, first year college students who have never written a line of code in their lives.

When our original textbook was written 11 years ago we made the conscious choice to ignore certain PEP8 conventions because we were in a world where we needed to prepare students to move into Java after one or two semesters of Python.  The common convention in that world was camelCase.  Our book, our decision.  In addition I will defend the tradeoff of making things fit onto one line to conform to the space requirements of a paper book.  PEP8 is a guideline, not a law.  You can disagree with the decisions we made, but you weren't there at the time.

Times have changed.  In the next revision, I would follow a lot more of the PEP8 guidelines, I would eliminate getters and setters, I would be better about using whitespace, particularly in an online book.   I would do lots of things different and take a much more Pythonic approach today.
