### ISSUE TITLE
Division by zero error in example

### ISSUE THREAD

**Issue by ronaldbradford** [RunestoneInteractive/RunestoneServer#588]
On http://interactivepython.org/runestone/static/pythonds/Introduction/DefiningFunctions.html you have the line  

root = (1/2)*(root + (n / root))

However, this results in 0 and a subsequent division by zero. Specifically you are performing integer precision and not float precision.

> > > 1/2
> > > 0
> > > 1/2.0
> > > 0.5

so 1/2 needs to be 1/2.0

Two lines preceding you also need to specify n/2.0 in order to address another inaccuracy.

**Comment by bnmnetp** [comment]
Hi,

This behavior depends on the version of Python you are using.  In Python 3 the semantics of / were changed so that 1/2 returns 0.5   -- The paper version of this book and subsequent interactive edition both use Python 3 semantics.

It probably would not hurt to make a bigger deal of this in the intro chapter so that everyone understands which version of / we are using by default.

**Comment by ronaldbradford** [comment]
Thanks.

You are correct, I was running 2.7. As I am relatively new to Python version specifics I was unaware of this particular semantic difference so good to know.  Regardless of adding a note on a different page, it may be of benefit to consider a footnote in examples for people searching and linking to a specific page of your site.   e.g. Works in 2.x/3.x or Works in 3.x only.

**Comment by bnmnetp** [comment]
Thanks for the suggestion, a footnote would be an excellent way to handle this.
