### ISSUE TITLE
Adding Discussion tab to all exercises

### ISSUE THREAD

**Issue by yonureker** [RunestoneInteractive/RunestoneServer#591]
Is it possible to add the discussion tab to all exercises? At least someone will post the correct answer so people can compare it to their solution.

For example here: http://interactivepython.org/runestone/static/thinkcspy/SimplePythonData/Exercises.html

**Comment by bnmnetp** [comment]
Hi, 

Of course it would be possible to add discussion tabs for all exercises.  Furthermore, I can understand why people who are working and learning on their own would like to have access to answers to all questions.   But because the book is used by many teachers as part of a class I do not want to publish the answers to all of the questions because too many students would simply copy the answers rather than work hard to discover the answers on their own.

So, until I figure out a better middle ground I will not provide discussion or answer tabs for the even numbered questions.

Suggestions welcome!

Brad
