### ISSUE TITLE
Invalidate session cookie after deleting a course

### ISSUE THREAD

**Issue by damienjadeduff** [RunestoneInteractive/RunestoneServer#627]
**Steps to cause error**: The root cause is that I created two courses, could not access the instructor page for the first, then deleted the second. Oops. Now nothing works when logged in with this account. I get something like:

    Internal error
    Ticket issued: runestone/160.75.27.148.2015-08-20.08-08-28.2f25d80e-7daa-4779-ad04-9bb95a522266

The first course is still accessible but not the instructor page instructor.

**Username**:  damienjadeduff
**Page that is causing trouble**: Most pages when logged in. E.g.:

 - <http://interactivepython.org/>
 - <http://interactivepython.org/runestone/admin/index>

**Comment by damienjadeduff** [comment]
Well I logged out and logged back in again and although I now can't access course #1, I do not get the error.

**Comment by bnmnetp** [comment]
So, the issue is that you can only be enrolled in one course at a time.  If you are an instructor and want to have two courses going then you should either create two accounts, or get used to changing your profile to go back and forth between courses.

The internal error was due to the fact that your session cookie did not get updated when you deleted course 2 and the system wanted to send you to the page for a course that no longer existed.  The logout/login fixed the session cookie.

To get back to accessing your first course again you should update your profile so that you are once again enrolled in that course.

**Comment by damienjadeduff** [comment]
Thank you.
