### ISSUE TITLE
New to programming-Unfamiliar with drag and drop in Turtle exercises

### ISSUE THREAD

**Issue by carolnpa** [RunestoneInteractive/RunestoneServer#649]
My name is Carolyn Casiano. I am 62 years old and attempting to complete the "How to Think Like a Computer Scientist" course. My computer skills are limited to an "Introduction to Computers" course at Delaware County Community College in Pennsylvania and picking up isolated skills from Microsoft Office on my own.
I'm using Amazon's Kindle Fire HD7 with Google's Chrome search engine.

I am unable to get hang of drag and drop to place block statements on drop side (from left side to right side) for exercises 2.2 to 2.4. 
Correct order of  mixed up programs of block statements:

2.2 Big L
1. import turtle
2. wn = turtle. Screen()
3. ella = turtle. Turtle()
4. ella. right(90)
5. ella. forward(150)
6. ella. left(90)
7. ella. forward(75)

2.3 Check mark
1. import turtle
2. wn = turtle. Screen()
3. maria = turtle. Turtle()
4. maria. right(45)
5. maria. forward(75)
6.maria. left(90)
7. maria.forward(150)

2.4 Single line
1. import turtle
2. wn = turtle. Screen()
3. jamal = turtle.Turtle()
4. jamal. left(180)
5.jamal. forward(75)

The mechanics of drag and drop are hard to grasp.

Thank you for your attention to this matter. My email address is casianoc704@gmail.com
Carolyn

**Comment by bnmnetp** [comment]
Hi Carolyn,

Sorry you are having trouble.   I don't have a kindle fire of any kind, so I cannot test it and see what is happening.  I know that the drag and drop exercises can be a challenge on the iPad and other tablets as well so it is not too surprising.  Unfortunately since the Amazon browser represents only 0.04% of my traffic its not something I'm going to be able to give much attention to anytime soon.

Brad

**Comment by carolnpa** [comment]
Thank you for your attention to this matter.
Carolyn
