### ISSUE TITLE
Wrong dequeue implementation on Implementing a Queue in Python Page

### ISSUE THREAD

**Issue by onur1313** [RunestoneInteractive/RunestoneServer#664]
On "Implementing a Queue in Python" page dequeue method is implemented wrong. pop() method would pop the last item in the list and returns but what we want when dequeue is called is returning the first element in the queue.

Error Line:
    def dequeue(self):
        return self.items.pop()

Should be:
    def dequeue(self):
        return self.items.pop(0)

**Comment by bnmnetp** [comment]
The dequeue method is implemented correctly as it is.  The reason is that enqueue adds to the beginning of the list using insert(0,foo).

Of course if we had implemented enqueue to simply append to the list then your comment would be correct.  Either way is an OK way to implement the queue as long as you are consistent.
