### ISSUE TITLE
Entering an invalid date when rebuilding the course == crasher

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#825]
**Raised by:** courselib@interactivepython.org<br>
``` Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/admin.py", line 1322, in 
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in 
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/tools.py", line 3022, in f
    return action(*a, **b)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/admin.py", line 298, in rebuildcourse
    curr_start_date = course.term_start_date.strftime("%m/%d/%Y")
ValueError: year=16 is before 1900; the datetime strftime() methods require year &gt;= 1900
 ```<br><br>

**Comment by bnmnetp** [comment]
Both admin and rebuildcourse in admin.py should validate the data entered before moving on.  Or perhaps we should just use the datepicker for these fields as well to be sure we have the correct format.

**Comment by millro04** [comment]
I think using the datepicker plugin is the best approach. Although, jQuery has a built in datepicker function that I should be able to call - `        $('#startdate').datepicker();` But I'm getting an error saying 'datepicker is not a function', which leads me to believe something might be wrong with loading jQuery. Aren't we always loading jQuery?
 I could also use the datetimepicker plugin (used in assignments.html) which we know already works, but I don't think that's consistent because the term_start_date field in courses table is only a date type, not datetime.

**Comment by millro04** [comment]
Scratch that, I got things working. Had to include an extra jQuery UI js and css file to get the plugin to work.

**Comment by bnmnetp** [comment]
OK, great!

At this point it would be really nice if you could start making nice small, focused PR's for each of these bugs your taking care of.  You'll probably have a few parallel branches going that you will switch between.  But it helps a lot to keep the PR's lined up with 1 or 2 Issues.
