### ISSUE TITLE
Proposal: associate grades and comments with questions instead of activecodes

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#840]
Currently, in the new grading interface (and the old), grades and comments are added as a column in the db.code table. This is done in assignments/problem. This clearly associates feedback with a particular code run, which has advantages and disadvantages. The big disadvantage is in how to surface the comment for the user.

As currently implemented, feedback is an available button on activecodes. It calls ajax/getassignmentgrade. It is currenlty not working correctly, because the query in there assumes the problem (the activecode) is associated with an assignment, rather than the activecode being associated with a question which is associated with an assignment. So that would have to be fixed in any case.

My proposal is:
1. When we save a comment and grade, they are associated with the question object rather than the code object. This will require:
   - database modification to add these fields for questions
   - change to the call to assignments/problem to be a call to a new endpoint assignments/gradequestion. It will work similarly, but save the result in the question's code table.
     One advantage of these changes is that we will have backward compatibility with the old grading system, which will use grades attached to code rows and the old assignments/problem endpoint. We can probably still use the old enpoint to get the source for the activecode, as we are presumably doing now, so that won't have to be reimplemented.
2. We add a bit of javascript to assignment html pages, which, after loading, gathers up all the question divids, makes a single ajax call to a new endpoint to get feedback on those, gets the response, and displays the feedback as a div at the top of each corresponding question. 
   Again, this preserves the Show Feedback button based on ajax/getassignmentgrade on actex's for backward compatibility.

**Comment by bnmnetp** [comment]
A long morning of faculty meetings ahead, but I wanted to comment here.

1.  I agree that associating the grade/comment for an activecode with a particular run in the code table is now the wrong thing to do.

2.  I disagree with putting the score in the question table.  There is no reason to make a copy of the question row for every student that gets a grade.

  I think we should create a table similar to the other xxx_answer tables for keeping track of the grades for activecodes.  This table would h ave columns for div_id, sid, course_name, score,  comments, and id_of_code_graded -- the div_id would match the div_id in the assignment and could be the divid of the actual ``.. activecode:: / .. actex::``  rather than the ``.. question::``

  That last field being the id of the row in the code table corresponding to the answer that was graded.


3.  I disagree with tying the feedback button to an assignment.  I don't know exactly when that happened, but as someone who has not used the assignment interface in my own courses I object to forcing instructors to use our interface when when we don't need to.  If a student presses the feedback button they ought to see the grade that is there if there is one.  I think students are perfectly capable of coping with the idea that sometimes we go back and regrade a particular problem if we have some reason to do so.

4.  I am in full support of including summary information on the assignment page, but I think we ought to break that out into a separate issue.

**Comment by presnick** [comment]
Based on skype call this morning, resolution is as follows.

1. We will continue to have grades associated with gradable elements, which are things like activecodes, not questions. A question is just a wrapper that allows for nice display of other stuff around a gradeable item.

2. We will move the actual grade and comment into a separate table, as described in Brad's number 2 in the previous comment. This will require the following changes:
  - create the new table
  - change assignments/problem to save the grade and comment in the new table
  - change ajax/getassignmentgrade to look up in the new table, so that Show Feedback button will continue to work
  - update other grading functions (e.g., computing totals for assignments) that were getting grades from the code table.

3. Creating a new issue for including summary information on the assignment page.

4. Creating a new issue for linking question ids with gradeable divids.
