### ISSUE TITLE
instructor activecode grading history slider

### ISSUE THREAD

**Issue by mhaugrud** [RunestoneInteractive/RunestoneServer#854]
It is great to have the history of student edits for an activecode. However I request the range of history that is available for the instructor be limited to the course start date and the assignment due date. The last save prior to the due date would be the default view. This change would expedite grading since 'invalid' dates would be eliminated and the edit closest before the due date would be displayed by default

**Comment by bnmnetp** [comment]
I hear what you are asking for, but the challenge is that not everyone has the same policy on grading late work.  Many instructors will look at the latest, and take off some points depending on how late the work is.  Others won't look at anything after the deadline.  Others have different policies.  I know its less convenient, but we will have to try to find a way to make this work for everyone.  Perhaps a simple flag on the assignment itself about how strict to be on deadlines will work.

**Comment by bnmnetp** [comment]
@presnick when I was looking at some grading code yesterday, it looked like there was some code in place for `request.vars.enforceDeadline`   Maybe we could add a checkbox to the assignment creation page that would determine the behavior of the history slider when grading.

The activecode component already knows when it is in "grading mode" so if we set another additional initialization parameter that included the deadline, we could send loadhist an end date so it would not return anything after the given date.

I say this because I think you and @mhaugrud have much more similar deadline policies than you and I or @mhaugrud and I.

**Comment by presnick** [comment]
My intention was for the enforce deadline checkbox on the grading page to
govern it. So it's up to the grader rather than the assignment creator.  I
*think* I already implemented that: if the checkbox is clicked, get_problem
is supposed to retrieve the last code before the deadline. I'm not sure if
that works correctly with the scrubber, though. I suspect not.

sent from mobile-- strange words are probably auto-correct gone awry.
