### ISSUE TITLE
Suddenly I have insufficient privileges as an instructor

### ISSUE THREAD

**Issue by jlshowngoshen** [RunestoneInteractive/RunestoneServer#941]
One day I had instructor privileges, now I don't.  
Any suggestions would be appreciated!
Thank you.

**Comment by bnmnetp** [comment]
Hmm, this is a new one...

For what course?  What is the username for your instructor account?

**Comment by bnmnetp** [comment]
Assuming that your username is `jlshown` it looks like you are set up in the database as the instructor for GCProgrammingI and GCProgrammingII  I can see that you have successfully built a course for GCProgrammingII but it does not look like you have built GCProgrammingI    Were you seeing a 404 for the GCProgrammingI course?

Which course were you having trouble with?  Did you try the change course option under the user menu?  

If you can change to the GCProgrammingI course then go to the instructor interface and request a rebuild for that course.

Brad

**Comment by jlshowngoshen** [comment]
jlshown is the username, and it doesn't matter which course.  When I go to the instructors page I don't have permissions to do any thing. I'm an associate professor of computing science at Goshen College btw.  I'm trying out your online books to save my students some money.  Thank you so much for doing this!

**Comment by jlshowngoshen** [comment]
Hello Brad, 
When I click on "Rebuild my course" from the instructors page it states: "You do not have sufficient privileges".  
![image](https://user-images.githubusercontent.com/21182008/27649003-6e67a6ea-5bfe-11e7-82b2-13578abcc703.png)

**Comment by jlshowngoshen** [comment]
And yes, I receive the 404 error on ProgrammingI.  
Thanks again,
Jeanette

**Comment by bnmnetp** [comment]
When I look at your record in the database it tells me that you are currently associated with the thinkcspy course.   You need to pull down the user menu and choose "Change Course" then select one of the courses you built.  You may want to copy the link to the instructors page to your clipboard so that when you get the 404 you can past that in.

If that doesn't work, I'm temporarily stumped.  I cannot recreate the problem for any of my test teacher accounts and I have not heard of this problem for anyone else.   Maybe you could look in the Javascript log to see if you are getting any errors there, as I'm not seeing any server side errors.

Brad

**Comment by jlshowngoshen** [comment]
Thank you Brad for your assistance, I was finally able to rebuild the course and it works.  Good advice.
