### ISSUE TITLE
Need a view/controller to dynamically create an assignment page

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#955]
Everything we need is already in the database, so it seems like it would make sense to generate assignment pages dynamically.

@presnick If you have ideas or a requirements for how you would like these pages to look let me know.

**Comment by presnick** [comment]
OK. If you're about to do this now, then maybe I won't bother to update the .rst generator for the instructor assignments tab.

For design, basically I think it should have three sections:
Top: title, deadline, and HTML generated from the description field (which authors can enter in restructured text when creating the assignment). Also show points available, which is either assignment.points_to_award (if threshold exists and is non-null) or assignment.points (otherwise).

Middle: Links to the reading assignment subchapters. Select the assignment_questions where reading_assignment is set to 'T'. These should be sorted according to the sorting_priority field in assignment_questions. Group by chapter with chapters as headings that are not links and subchapters as links, sort of .toc style.  We might want to design this from the start to show the student's progress, if the subchapter is graded, perhaps something like what is shown in the screenshot at the bottom, but prettier.

Bottom: Embedded exercises. Select the assignment_questions where reading_assignment is not 'T', again sorted by sorting_priority. For each one, just dump the .html associated with the question into the page. We might want to design this from the start to show points and comments from instructor for graded items, if grades have been released. 

![image](https://user-images.githubusercontent.com/1077198/27975522-7e21d7de-6330-11e7-8557-bcdd15d07817.png)

**Comment by bnmnetp** [comment]
Ok, I was just sketching...

![note jul 7 2017](https://user-images.githubusercontent.com/51115/27975651-c1a07cca-6328-11e7-826d-580ff47d508b.png)

**Comment by bnmnetp** [comment]
I think we are ahead to spend our time getting this to work, which I don't think will be hard. Rather than updating the rst generator.   If we get the right template with the right CSS/JS files in it and I think we are good, and potentially much better than where we are today.  But if you can think of a good reason to force a rebuild let me know.

*Note:* One caveat which I want to document here is that the previewer runs in a mode where it does not write to the database.  Maybe it should or we need to have a save button that causes the final html to be written to the DB with the question.

**Comment by bnmnetp** [comment]
I could work on this, or it might be a good one for @gardhi01 and @conzty01 to take on when they are done with the auto grading stuff.  In either case I think we can have it finished up in a week.

**Comment by bnmnetp** [comment]
Making good progress on this.  One challenge I noticed is for components that have images in them.  when we move the base url for the component to this page it does not show up.

One easy solution would be to require that we use an absolute reference for images in questions.

Other ideas?
