### ISSUE TITLE
Assignments lack links to their containing chapter

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#979]
In an assignment, there's no link to go to the chapter containing the assignment. So, I was guessing on turtle orientation, and had to manually find the chapter to make some sense of it.

**Comment by bnmnetp** [comment]
What do you think makes the most sense for how adding a link?

Since each question has the chapter/subchapter info associated with it, I could imagine the htmlsrc endpoint returning that in addition to the htmlsrc.  Then the render function could add a link at the end of the runestone div that would take you to that chapter and subchapter.

Maybe the link would say:  "Show this question in context" or something like that.

**Comment by bjones1** [comment]
Perhaps a link "Chapter Title / Subchapter Title, with the appropriate titles filled in an both hyperlinked appropriately? What does Paul do with his usageassignment directive? Perhaps he already does something like this?

**Comment by bnmnetp** [comment]
Done
