### ISSUE TITLE
Scoring of activities in reading section 1.4 

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#995]
Test: Assign all 5 activities in section 1.4, do all of them and then check score
Where: LHSIntroCS book, Assignment Try9

In section 1.4, if all 5 activities are required in the Assignment, when student does everything, the auto-grade scores it as a 0.

@bnmnetp You had mentioned codelens grading could be the issue on this one. Logging the issue for tracking purposes.

**Comment by bnmnetp** [comment]
I think I finally tracked this down to the root cause, I was able to reproduce it and fix it.  

For future reference, the root problem was that two chapters were using the same id for the same codelens example.  --- This is bad and should be detected during the build.  So, the codelens problem was not getting graded (or even included in the possible activities because there was not record of it for this chapter/subchapter)   Secondly, the autograder for the activecode was making a bad assumption that there should be a unittest in order to provide a grade.  I added logic to notice that it was an 'interact' autograde instead.

**Note** It will require a rebuild of your course to make sure that the DB is in good working order.
